### ISSUE TITLE
UAT: Dashboard Leave Team (UI) not working as it should

### ISSUE THREAD

**Issue by LachlanWilliams** [Monash-FIT3170/Onboarder#74]
When a user leave a team the dashboard doesn't update. Reloading the page removes everything from the table view. But after a while refreshing again it comes back.

**Comment by JesseCr00** [comment]
Additional Info:
For this table, and potentially others, we need to make sure new items are updated straight away.
We should also cache items if possible so it is not slow on refresh. (If we fix the app speed problem, this may not be an issue)

**Comment by Rahul-Saxena-1** [comment]
Should be addressed in the ui role PR

**Comment by JesseCr00** [comment]
Fixed
