### ISSUE TITLE
UAT: Users can submit duplicate applications

### ISSUE THREAD

**Issue by JesseCr00** [Monash-FIT3170/Onboarder#87]
Bug/Problem from UAT Form:
Prevent users from applying to a role multiple times

Additional Notes:
We need to add a check to make sure a user cannot apply to the same role twice.
Optional extension: Prompt the user if they wanted to update the previous application (replace previous one with new one)

**Comment by Rahul-Saxena-1** [comment]
Fix should be included in new PR
