### ISSUE TITLE
UAT: Team Creation does not persist across refresh

### ISSUE THREAD

**Issue by JesseCr00** [Monash-FIT3170/Onboarder#88]
Bug/Problem from UAT Form: 
Creation of teams did not seem to persist across refreshes

**Comment by Rahul-Saxena-1** [comment]
not sure what this means lol, the team disappeared on refresh?, probs not updated on supabase? 
will need to understand the issue first if we do this

**Comment by Rahul-Saxena-1** [comment]
I believe this was due to the profile_id shenanigans we had to before Supabase had data for everyone. Will need to be tested again @JesseCr00

**Comment by JesseCr00** [comment]
Fixed this.
